### ISSUE TITLE
Why  hotspot stop after a period of time?

### ISSUE THREAD

**Issue by hdytyldrm** [aegis1980/WifiHotSpot#12]

**Comment by djvergad** [comment]
@hdytyldrm What android version are you on? On Pie hotspot turns off automatically if no devices are connected for a period of time. You can change that setting form `Settings` --> `Network & internet` --> `Hotspot & tethering` --> `Wi-Fi hotspot` --> `Advanced` --> `Turn off hotspot automatically`

**Comment by hdytyldrm** [comment]
> @hdytyldrm What android version are you on? On Pie hotspot turns off automatically if no devices are connected for a period of time. You can change that setting form `Settings` --> `Network & internet` --> `Hotspot & tethering` --> `Wi-Fi hotspot` --> `Advanced` --> `Turn off hotspot automatically`

**Comment by hdytyldrm** [comment]
> > @hdytyldrm What android version are you on? On Pie hotspot turns off automatically if no devices are connected for a period of time. You can change that setting form `Settings` --> `Network & internet` --> `Hotspot & tethering` --> `Wi-Fi hotspot` --> `Advanced` --> `Turn off hotspot automatically`

Thanks for answer.Is there any way do this programmatically?
