### ISSUE TITLE
Use ProxyBuilder for OnStartTetheringCallback

### ISSUE THREAD

**Issue by Mygod** [aegis1980/WifiHotSpot#2]
Cool demo. There's a convenient class called `ProxyBuilder` that can help you instantiate an `OnStartTetheringCallback`. For example see [here](https://github.com/Mygod/VPNHotspot/commit/958b1ec35043a364291d84ad0134599890991a0e#diff-55261853cc581a823fba13049cd13514R91).

An unrelated question: is location permission needed?

**Comment by aegis1980** [comment]
Sweet - glad was useful. Will give `ProxyBuilder` a go.

Thought you need coarse location permission for wifi? Maybe only for turning on and off wifi or checking state. Dunno. Will take it out of manifest see if it spits the dummy.

**Comment by Mygod** [comment]
I think you only need it for scanning. Your demo works fine on my side
without location permissions.
